### User save
POST http://localhost:8080/user/save
Content-Type: application/json

{
  "id": "1234567890",
  "name": "123",
  "token": "AW3#!FAWEFA123"
}

### User List 조회
GET http://localhost:8080/user/list

### User Id로 조회
GET http://localhost:8080/user/getuser?id=12342323
